package detect

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"sandbox/internal/core"
)

const SandboxSettingsModule = "jr_sandbox_settings"

type djangoProject struct {
	Dir      string // absolute directory containing manage.py
	Rel      string // that directory relative to the clone root, forward slashes
	Settings string // dotted settings module, e.g. "config.settings"
}

// Vendored, virtual-env and scaffolding trees: a manage.py here is not the app.
func skipDir(name string) bool {
	switch name {
	case "node_modules", "__pycache__", "venv", "env", ".venv", "site-packages", "migrations",
		"builder-template", "template", "templates", "example", "examples",
		"sample", "samples", "fixtures", "testdata", "vendor":
		return true
	}
	return strings.HasPrefix(name, ".")
}

// Breadth-first to 3 levels, so the shallowest manage.py wins.
func findDjangoProject(root string) (djangoProject, bool) {
	type candidate struct{ dir, rel string }
	queue := []candidate{{root, ""}}

	for depth := 0; depth <= 3 && len(queue) > 0; depth++ {
		var next []candidate
		for _, c := range queue {
			if core.FileExists(filepath.Join(c.dir, "manage.py")) {
				return newDjangoProject(c.dir, c.rel), true
			}
			if depth == 3 {
				continue
			}
			entries, err := os.ReadDir(c.dir)
			if err != nil {
				continue
			}
			for _, e := range entries {
				if !e.IsDir() || skipDir(e.Name()) {
					continue
				}
				rel := e.Name()
				if c.rel != "" {
					rel = c.rel + "/" + e.Name()
				}
				next = append(next, candidate{filepath.Join(c.dir, e.Name()), rel})
			}
		}
		queue = next
	}
	return djangoProject{}, false
}

func newDjangoProject(dir, rel string) djangoProject {
	p := djangoProject{Dir: dir, Rel: rel}
	src, _ := os.ReadFile(filepath.Join(dir, "manage.py"))
	p.Settings = DjangoSettingsModule(string(src))
	if p.Settings == "" {
		p.Settings = findSettingsPackage(dir)
	}
	return p
}

// Read the module manage.py names — it is often not <projectname>.settings.
var settingsModuleRe = regexp.MustCompile(`DJANGO_SETTINGS_MODULE["']\s*,\s*["']([^"']+)["']`)

func DjangoSettingsModule(manageSrc string) string {
	m := settingsModuleRe.FindStringSubmatch(manageSrc)
	if len(m) < 2 {
		return ""
	}
	return strings.TrimSpace(m[1])
}

// Fallback: the config package is the one with both settings.py and wsgi.py.
func findSettingsPackage(dir string) string {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return ""
	}
	for _, e := range entries {
		if !e.IsDir() || skipDir(e.Name()) {
			continue
		}
		sub := filepath.Join(dir, e.Name())
		if core.FileExists(filepath.Join(sub, "settings.py")) && core.FileExists(filepath.Join(sub, "wsgi.py")) {
			return e.Name() + ".settings"
		}
		if core.FileExists(filepath.Join(sub, "settings", "base.py")) && core.FileExists(filepath.Join(sub, "wsgi.py")) {
			return e.Name() + ".settings.base"
		}
	}
	return ""
}

// Star-import first, so the overrides below win.
func sandboxSettingsSource(realModule string) string {
	return fmt.Sprintf(`"""Generated by Jr Architect for the sandbox preview — not part of the app.

Imports %s unchanged and overrides only what a containerised preview needs.
Edit the app's real settings module for changes you want to keep.
"""

from %s import *  # noqa: F401,F403

# The preview reaches the app on 127.0.0.1:<random port>; without this it 400s.
ALLOWED_HOSTS = ["*"]

# Serves static files without collectstatic, and shows a traceback over a bare 500.
DEBUG = True

# Only fills a gap when the repo reads SECRET_KEY from an unset env var.
if not globals().get("SECRET_KEY"):
    SECRET_KEY = "jr-architect-sandbox-key-not-for-production"
`, realModule, realModule)
}

// Returns the module to boot with, or "" when there is nothing to star-import.
func writeSandboxSettings(p djangoProject) string {
	if p.Settings == "" {
		return ""
	}
	dest := filepath.Join(p.Dir, SandboxSettingsModule+".py")
	if err := os.WriteFile(dest, []byte(sandboxSettingsSource(p.Settings)), 0644); err != nil {
		fmt.Printf("[django] could not write %s: %v — booting the app's own settings\n", dest, err)
		return ""
	}
	return SandboxSettingsModule
}

// Prefers a manifest beside manage.py. Paths come back relative to the service
// directory, because that is where the install step runs.
func djangoInstallCommand(root string, p djangoProject) string {
	names := []string{
		"requirements.txt",
		"requirements/dev.txt", "requirements/local.txt", "requirements/development.txt",
		"requirements/base.txt", "requirements-dev.txt",
	}
	for _, dir := range []string{p.Rel, ""} {
		for _, n := range names {
			if core.FileExists(filepath.Join(root, filepath.FromSlash(joinRel(dir, n)))) {
				return "pip install -r " + upTo(p.Rel, dir) + n
			}
		}
		if core.FileExists(filepath.Join(root, filepath.FromSlash(joinRel(dir, "Pipfile")))) {
			return "pip install pipenv && pipenv install --system --skip-lock"
		}
		if core.FileExists(filepath.Join(root, filepath.FromSlash(joinRel(dir, "pyproject.toml")))) {
			return "pip install " + strings.TrimSuffix(upTo(p.Rel, dir), "/") + dotIfEmpty(upTo(p.Rel, dir))
		}
		if p.Rel == "" {
			break // root and project dir are the same
		}
	}
	return "" // no manifest: the image already ships Django
}

// The "../" hops from the service directory back to where the manifest actually is.
func upTo(serviceRel, manifestDir string) string {
	if serviceRel == manifestDir {
		return ""
	}
	return strings.Repeat("../", strings.Count(serviceRel, "/")+1)
}

func dotIfEmpty(prefix string) string {
	if prefix == "" {
		return "."
	}
	return ""
}

func joinRel(dir, name string) string {
	if dir == "" {
		return name
	}
	return dir + "/" + name
}
