package builder

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// What a route is about, to the icon its nav item gets; the first keyword found in the route or its name wins.
var navIconWords = [][2]string{
	{"home", "Home"}, {"dashboard", "LayoutDashboard"}, {"overview", "LayoutDashboard"}, {"today", "Sun"},
	{"recipe", "BookOpen"}, {"cook", "ChefHat"}, {"meal", "UtensilsCrossed"}, {"pantry", "ShoppingBasket"}, {"grocer", "ShoppingCart"}, {"shopping", "ShoppingCart"},
	{"plan", "CalendarDays"}, {"calendar", "CalendarDays"}, {"schedule", "CalendarDays"}, {"roadmap", "Map"},
	{"lesson", "GraduationCap"}, {"course", "GraduationCap"}, {"learn", "GraduationCap"}, {"quiz", "ListChecks"}, {"practice", "Dumbbell"},
	{"editor", "Code2"}, {"code", "Code2"}, {"sandbox", "Code2"}, {"playground", "Code2"},
	{"progress", "TrendingUp"}, {"stats", "BarChart3"}, {"analytic", "BarChart3"}, {"report", "FileBarChart"}, {"insight", "Lightbulb"},
	{"task", "CheckSquare"}, {"todo", "CheckSquare"}, {"board", "KanbanSquare"}, {"project", "FolderKanban"}, {"goal", "Target"}, {"habit", "Repeat"},
	{"inbox", "Inbox"}, {"mail", "Mail"}, {"message", "MessageSquare"}, {"chat", "MessageSquare"}, {"coach", "Sparkles"}, {"assistant", "Bot"}, {"ai", "Sparkles"},
	{"note", "NotebookPen"}, {"journal", "NotebookPen"}, {"doc", "FileText"}, {"library", "Library"}, {"collection", "Bookmark"}, {"favorite", "Heart"}, {"saved", "Bookmark"},
	{"explore", "Compass"}, {"discover", "Compass"}, {"search", "Search"}, {"browse", "Compass"},
	{"budget", "Wallet"}, {"expense", "Receipt"}, {"invoice", "Receipt"}, {"finance", "Wallet"}, {"transaction", "ArrowLeftRight"},
	{"workout", "Dumbbell"}, {"fitness", "Activity"}, {"health", "HeartPulse"}, {"sleep", "Moon"},
	{"contact", "Users"}, {"client", "Users"}, {"customer", "Users"}, {"team", "Users"}, {"people", "Users"},
	{"history", "History"}, {"archive", "Archive"}, {"export", "Download"}, {"profile", "User"}, {"account", "User"}, {"setting", "Settings"}, {"preference", "SlidersHorizontal"}, {"help", "LifeBuoy"},
}

func navIcon(route, name string) string {
	hay := strings.ToLower(route + " " + name)
	if route == "/" {
		hay = "home " + hay
	}
	for _, w := range navIconWords {
		if strings.Contains(hay, w[0]) && lucideIcons[w[1]] {
			return w[1]
		}
	}
	return "LayoutGrid"
}

type shellItem struct{ href, label, icon string }

// One nav item per real page, so the shell never links to a route that was not generated.
func shellItems(prd *PRD, react bool) []shellItem {
	var items []shellItem
	if react {
		for _, v := range viewsOf(prd) {
			items = append(items, shellItem{v.Slug, v.Name, navIcon(v.Route, v.Name)})
		}
		return items
	}
	for _, rt := range parsePRDRoutes(prd) {
		name, _, _ := strings.Cut(rt.name, ":")
		name = strings.TrimSpace(name)
		if name == "" {
			name = "Home"
		}
		items = append(items, shellItem{rt.route, name, navIcon(rt.route, name)})
	}
	if len(items) == 0 {
		items = append(items, shellItem{"/", "Home", "Home"})
	}
	return items
}

func shellVariant(prd *PRD) string {
	if prd.Design == nil {
		return "sidebar"
	}
	switch prd.Design.Navigation {
	case "top", "none":
		return "topbar"
	case "bottom":
		return "bottom"
	}
	return "sidebar"
}

func brandIcon(prd *PRD) string {
	if prd.Design != nil && lucideIcons[prd.Design.BrandIcon] {
		return prd.Design.BrandIcon
	}
	return "Sparkles"
}

var jsString = regexp.MustCompile(`[\\"\n\r<>]`)

// A double-quoted JS string that cannot break out of the file it is written into.
func jsQuote(s string) string {
	return `"` + jsString.ReplaceAllStringFunc(s, func(c string) string {
		switch c {
		case "\n", "\r":
			return " "
		case "<":
			return `\x3c`
		case ">":
			return `\x3e`
		}
		return `\` + c
	}) + `"`
}

func shellImports(items []shellItem, brand string) string {
	seen := map[string]bool{brand: true}
	names := []string{brand}
	for _, it := range items {
		if !seen[it.icon] {
			seen[it.icon] = true
			names = append(names, it.icon)
		}
	}
	sort.Strings(names)
	return strings.Join(names, ", ")
}

// Next.js: the app frame around every page, written by the server from the routes and the design direction.
func writeNextShell(workdir string, prd *PRD) error {
	items := shellItems(prd, false)
	brand := brandIcon(prd)
	var nav []string
	for _, it := range items {
		nav = append(nav, fmt.Sprintf("  { href: %s, label: %s, icon: %s },", jsQuote(it.href), jsQuote(it.label), it.icon))
	}
	src := fmt.Sprintf(`"use client";

// Generated by Build mode from the app's pages and design direction; the layout itself lives in @/components/blocks.
import * as React from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { %s } from "lucide-react";
import { AppShell as Shell, type NavItem } from "@/components/blocks";

const nav: NavItem[] = [
%s
];

export function AppShell({ children, actions }: { children: React.ReactNode; actions?: React.ReactNode }) {
  const pathname = usePathname() || "/";
  return (
    <Shell brand={%s} brandIcon={%s} nav={nav} current={pathname} variant=%q linkComponent={Link} actions={actions}>
      {children}
    </Shell>
  );
}
`, shellImports(items, brand), strings.Join(nav, "\n"), jsQuote(prd.Name), brand, shellVariant(prd))
	return writeFile(workdir, "components/app/app-shell.tsx", src)
}

// React + Vite: the same frame, switching views by state instead of routes.
func writeReactFrame(workdir string, prd *PRD) error {
	items := shellItems(prd, true)
	brand := brandIcon(prd)
	var nav []string
	for _, it := range items {
		nav = append(nav, fmt.Sprintf("  { href: %s, label: %s, icon: %s },", jsQuote(it.href), jsQuote(it.label), it.icon))
	}
	src := fmt.Sprintf(`// Generated by Build mode from the app's views and design direction; the layout itself lives in @/components/blocks.
import { %s } from "lucide-react";
import { AppShell } from "@/components/blocks";

const nav = [
%s
];

export function AppFrame({ view, setView, actions, children }) {
  return (
    <AppShell brand={%s} brandIcon={%s} nav={nav} current={view} onNavigate={setView} variant=%q actions={actions}>
      {children}
    </AppShell>
  );
}
`, shellImports(items, brand), strings.Join(nav, "\n"), jsQuote(prd.Name), brand, shellVariant(prd))
	return writeFile(workdir, "src/components/app/AppFrame.jsx", src)
}

func writeFile(workdir, rel, content string) error {
	abs := filepath.Join(workdir, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(abs), 0755); err != nil {
		return err
	}
	return os.WriteFile(abs, []byte(content), 0644)
}

// The layout blocks every React screen is composed from.
const blocksReference = `
LAYOUT BLOCKS (already in @/components/blocks; import { ... } from "@/components/blocks"; never generate or copy them). Compose every screen from these; write your own components/app/* files only for what is unique to this app:
- <Page title description? eyebrow? actions?>...</Page>: every screen's outer wrapper and header (the app shell is already around it).
- <Hero eyebrow? title description? actions? aside?/>: a tinted headline banner for the screen's key moment.
- <Section title? description? actions? variant="card"|"plain">...</Section>: a titled group of content.
- <StatGrid><StatCard label value icon={Icon} delta?={12} deltaLabel? trend?={[numbers]} hint?/></StatGrid>: headline numbers.
- <BarChart data={[{ label, value }]} format? height?/>, <Sparkline data={[numbers]}/>, <ProgressRing value={0-100} label?/>.
- <DataTable columns={[{ key, header, render?: (row) => node, sortable?, hideOnMobile? }]} rows={items} searchKeys={["name"]} onRowClick? toolbar?/>.
- <CardGrid size="sm"|"md"|"lg"> of <MediaCard title subtitle? icon={Icon} seed? meta?={[{ icon, label }]} badges?={[nodes]} actions? onClick?/>; <CoverArt icon={Icon} seed ratio?/> for artwork anywhere.
- <ListDetail list={node} detail={node} showDetail={bool} onBack/> and <SplitLayout main={node} side={node} sideWidth?/>.
- <FilterBar query onQuery placeholder actions?>{<ChipGroup options value onChange multiple?/>}</FilterBar>.
- <Board columns={[{ id, title, items: [{ id, title, subtitle?, badge? }] }]} onMove?={(itemId, toColumn) => ...} onOpen?/>.
- <Stepper steps={[labels]} current={index}/>, <Timeline items={[{ title, description?, time?, icon? }]}/>.
- <AIPanel title description? actionLabel onRun running error inputs?={node} copyText?>{result}</AIPanel>: the home of every AI feature. <ChatPanel messages={[{ role: "user"|"assistant", content }]} onSend busy suggestions?/>: conversations.`

// This screen's plan from the design direction, as prompt text.
func screenPlan(prd *PRD, route string) string {
	if prd.Design == nil {
		return ""
	}
	for _, s := range prd.Design.Screens {
		if staticRoute(strings.TrimSpace(s.Route)) == route || (route == "/" && (s.Route == "home" || s.Route == "")) {
			var b strings.Builder
			fmt.Fprintf(&b, "\nSCREEN PLAN for %s (decided by the art director; build exactly this layout):\n- Layout: %s\n", route, s.Layout)
			for _, sec := range s.Sections {
				fmt.Fprintf(&b, "- %s\n", sec)
			}
			return b.String()
		}
	}
	return ""
}
