// lib/data.ts
// AI will replace this file with real mock data shaped to the PRD's data model.
// This is just a placeholder so TypeScript doesn't complain.

export const placeholder = {
  message: "Data will be generated by Jr Architect based on your PRD.",
};
